Repository brooksryba/Alpha, pull requests merged in 2022-09, with the labels that each got.

#134 Fixed bug with spell animations
  Assets/Classes/Controllers/Battle/Managers/BattleObjectManager.cs
  Assets/Classes/Controllers/Battle/States/AnimationStates/BattleStateAttackAnimationApproach.cs
  Assets/Classes/Controllers/Battle/States/AnimationStates/BattleStateAttackAnimationEffects.cs
  Assets/Classes/Controllers/Battle/States/AnimationStates/BattleStateSpellAnimationApproach.cs
  Assets/Classes/Controllers/Battle/States/AnimationStates/BattleStateSpellAnimationApproach.cs.meta
  Assets/Classes/Controllers/Battle/States/AnimationStates/BattleStateSpellAnimationEffects.cs
  Assets/Classes/Controllers/Battle/States/AnimationStates/BattleStateSpellAnimationEffects.cs.meta
  Assets/Classes/Controllers/Battle/States/AnimationStates/BattleStateSpellAnimationRetreat.cs
  Assets/Classes/Controllers/Battle/States/AnimationStates/BattleStateSpellAnimationRetreat.cs.meta
  Assets/Classes/Controllers/Battle/States/AttackStates/BattleStateEnemyAttack.cs
  Assets/Classes/Controllers/Battle/States/MinigameStates/BattleStateAttackMinigame.cs
  Assets/Resources/Prefabs/Characters/AttackEffects.prefab
  Assets/Resources/Prefabs/Characters/Livar.prefab
Labels: bug

#146 Basic time tracking system with color interpolation for global light
  Assets/Classes/Systems/CameraSystem.cs
  Assets/Classes/Systems/CameraSystem.cs.meta
  Assets/Resources/Prefabs/Systems/CameraSystem.prefab
Labels: base

#147 Fixtures for SaveSystem and replace Scriptables
  Assets/Classes/Controllers/Battle/Managers/BattleObjectManager.cs
  Assets/Classes/Controllers/Battle/States/SetupBreakdown/BattleStateEnd.cs
  Assets/Classes/Controllers/Battle/States/SetupBreakdown/BattleStateResign.cs
  Assets/Classes/Controllers/Player/CharacterMovement.cs
  Assets/Classes/Controllers/Player/PlayerControl.cs
  Assets/Classes/Controllers/Player/PlayerInteraction.cs
  Assets/Classes/Models/Character.cs
  Assets/Classes/Models/Cutscene.cs
  Assets/Classes/Models/InventoryItem.cs
  Assets/Classes/Models/Serializable/BattleData.cs
  Assets/Classes/Models/Serializable/BattleData.cs.meta
  Assets/Classes/Models/Serializable/CharacterData.cs
  Assets/Classes/Models/Serializable/CutsceneData.cs
  Assets/Classes/Models/Serializable/PlayerLocationData.cs
  Assets/Classes/Models/Serializable/SaveData.cs
  Assets/Classes/Models/Serializable/SaveData.cs.meta
  Assets/Classes/Systems/CutsceneSystem.cs
  Assets/Classes/Systems/MenuSystem.cs
  Assets/Classes/Systems/SaveSystem.cs
  Assets/Classes/Systems/SceneSystem.cs
  Assets/Classes/Systems/SceneSystem.cs.meta
  Assets/Classes/Systems/SettingsSystem.cs
  Assets/Classes/Systems/StorySystem.cs
  Assets/Classes/Systems/Systems.cs
  Assets/Classes/Systems/Systems.cs.meta
  Assets/Editor.meta
  Assets/Editor/SystemsInspector.cs
  Assets/Editor/SystemsInspector.cs.meta
  Assets/Plugins/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Anton SDF.asset
  Assets/Plugins/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Electronic Highway Sign SDF.asset
  Assets/Resources/Fixtures.meta
  Assets/Resources/Fixtures/sample.json
  Assets/Resources/Fixtures/sample.json.meta
  Assets/Resources/Prefabs/Systems/SaveSystem.prefab
  Assets/Resources/Prefabs/Systems/Systems.prefab
  Assets/Resources/Scriptable/BattleSceneScriptable.asset
  Assets/Resources/Scriptable/BattleSceneScriptable.asset.meta
  Assets/Resources/Scriptable/BattleSceneScriptable.cs
  Assets/Resources/Scriptable/PlayerScriptable.asset
  Assets/Resources/Scriptable/PlayerScriptable.cs
Labels: performance

#150 Use LeanTween for System prefabs
  Assets/Classes/Systems/CutsceneSystem.cs
  Assets/Classes/Systems/DialogSystem.cs
  Assets/Classes/Systems/ToastSystem.cs
  Assets/Plugins/LeanTween.meta
  Assets/Plugins/LeanTween/Framework.meta
  Assets/Plugins/LeanTween/Framework/LTDescr.cs
  Assets/Plugins/LeanTween/Framework/LTDescr.cs.meta
  Assets/Plugins/LeanTween/Framework/LTDescrOptional.cs
  Assets/Plugins/LeanTween/Framework/LTDescrOptional.cs.meta
  Assets/Plugins/LeanTween/Framework/LTSeq.cs
  Assets/Plugins/LeanTween/Framework/LTSeq.cs.meta
  Assets/Plugins/LeanTween/Framework/LeanAudio.cs
  Assets/Plugins/LeanTween/Framework/LeanAudio.cs.meta
  Assets/Plugins/LeanTween/Framework/LeanSmooth.cs
  Assets/Plugins/LeanTween/Framework/LeanSmooth.cs.meta
  Assets/Plugins/LeanTween/Framework/LeanTest.cs
  Assets/Plugins/LeanTween/Framework/LeanTest.cs.meta
  Assets/Plugins/LeanTween/Framework/LeanTween.cs
  Assets/Plugins/LeanTween/Framework/LeanTween.cs.meta
  Assets/Plugins/LeanTween/Framework/LeanTween.dll.zip
  Assets/Plugins/LeanTween/Framework/LeanTween.dll.zip.meta
  Assets/Plugins/LeanTween/Framework/LeanTweenExt.cs
  Assets/Plugins/LeanTween/Framework/LeanTweenExt.cs.meta
  Assets/Plugins/LeanTween/License.txt
  Assets/Plugins/LeanTween/License.txt.meta
  Assets/Plugins/LeanTween/ReadMe.txt
  Assets/Plugins/LeanTween/ReadMe.txt.meta
  Assets/Resources/Dialogue/Chapters/Chapter_1_1.ink
  Assets/Resources/Dialogue/Chapters/Chapter_1_1.json
  Assets/Resources/Prefabs/Systems/CutsceneSystem.prefab
  Assets/Resources/Prefabs/Systems/DialogSystem.prefab
  Assets/Resources/Prefabs/Systems/ToastSystem.prefab
  Assets/Scenes/World_Main_0.unity
Labels: enhancement

#145 XP leveling system w/ attack progression
  Assets/Classes/Controllers/Battle/BattleMoves/Attacks/HeavyAttack.cs
  Assets/Classes/Controllers/Battle/BattleMoves/Attacks/VeryHeavyAttack.cs
  Assets/Classes/Controllers/Battle/BattleMoves/Spells/BoostPhysicalAttack.cs
  Assets/Classes/Controllers/Battle/BattleMoves/Spells/Heal.cs
  Assets/Classes/Controllers/Battle/BattleMoves/Spells/ImmobilizeSpell.cs
  Assets/Classes/Controllers/Battle/BattleMoves/Spells/PoisonSpell.cs
  Assets/Classes/Controllers/Battle/Misc/BattleBonus.cs
  Assets/Classes/Controllers/Battle/States/SetupBreakdown/BattleStateEnd.cs
  Assets/Classes/Controllers/Player/PlayerControl.cs
  Assets/Classes/Models/Character.cs
  Assets/Classes/Models/CharacterTypes/BaseCharacterClass.cs
  Assets/Classes/Models/CharacterTypes/Jack.cs
  Assets/Classes/Models/ItemTypes/ToxicGem.cs
  Assets/Classes/Models/Serializable/CharacterData.cs
  Assets/Classes/Systems/LevelSystem.cs
  Assets/Classes/Systems/LevelSystem.cs.meta
  Assets/Resources/Prefabs/Characters/Player.prefab
  Assets/Resources/Prefabs/Systems/LevelSystem.prefab
  Assets/Resources/Prefabs/Systems/LevelSystem.prefab.meta
  Assets/Resources/Prefabs/Systems/Systems.prefab
  Assets/Scenes/Battle.unity
Labels: base

#153 Fix player animation add fifth frame
  Assets/Classes/Controllers/Player/CharacterMovement.cs
  Assets/Resources/Animations/Characters/Walk_Down.anim
  Assets/Resources/Animations/Characters/Walk_Left.anim
  Assets/Resources/Animations/Characters/Walk_Right.anim
  Assets/Resources/Animations/Characters/Walk_Up.anim
Labels: bug
